name: security_scan

on:
  push:

jobs:
    security_scan:
        runs-on: ubuntu-latest
        permissions:
            # Required for all workflows
            security-events: write
            # Only required for workflows in private repositories
            actions: read
            contents: read          
        steps:
          - name: Checkout repository
            uses: actions/checkout@v6

          - name: pip audit
            uses: pypa/gh-action-pip-audit@v1.1.0
            with:
              inputs: Python/Flask_Book_Library/requirements.txt
          
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.10' 
    
          - name: Run Bandit
            run: |
              pip install bandit
              cd Python/Flask_Book_Library
              bandit -r .

          - name: Deploy for DAST analysis
            uses: appleboy/ssh-action@v1
            with:
              host: ${{ secrets.DAST_HOST }}
              username: ${{ secrets.DAST_USER }}
              key: ${{ secrets.DAST_KEY }}
              port: 22
              script: |
                git clone https://github.com/${{ github.repository }}
                cd TBO_balbinka/Python/Flask_Book_Library
                git checkout ${{ github.sha }}
                docker build -t balbinkatest .
                docker container rm --force dast
                docker run -p 5000:5000 --name dast -d balbinkatest

          - name: zap scan
            uses: zaproxy/action-full-scan@v0.13.0
            with:
              target: 'http://${{ secrets.DAST_HOST }}:5000'
              allow_issue_writing: false
              fail_action: true
              cmd_options: '-I'

          - name: Teardown after DAST
            if: always()
            uses: appleboy/ssh-action@v1
            with:
              host: ${{ secrets.DAST_HOST }}
              username: ${{ secrets.DAST_USER }}
              key: ${{ secrets.DAST_KEY }}
              port: 22
              script: |
                docker stop dast
                docker container rm dast
                docker image rm balbinkatest
                rm -rf TBO_balbinka
