name: security_scan
on:
  push:
env:
  docker-tag: ${{ github.base_ref == 'main' && 'latest' || 'beta' }}
concurrency:
  group: cicd-sast-dast-docker
  cancel-in-progress: true
jobs:
    security_scan:
        runs-on: ubuntu-latest
        permissions:
            # Required for all workflows
            security-events: write
            # Only required for workflows in private repositories
            actions: read
            contents: read          
        steps:
          - name: Checkout repository
            uses: actions/checkout@v6

          - name: pip audit
            uses: pypa/gh-action-pip-audit@v1.1.0
            with:
              inputs: Python/Flask_Book_Library/requirements.txt
          - name: Bandit Scan
          
            uses: shundor/python-bandit-scan@v1.0

          - name: Upload Bandit Artifact
            uses: github/codeql-action/upload-sarif@v3
            if: always()
            with:
              sarif_file: results.sarif

          - name: Deploy for DAST analysis
            uses: appleboy/ssh-action@v1
            with:
              host: ${{ secrets.DAST_HOST }}
              username: ${{ secrets.DAST_USER }}
              key: ${{ secrets.DAST_KEY }}
              port: 22
              script: |
                git clone https://github.com/${{ github.repository }}
                cd TBO_balbinka/Python/Flask_Book_Library
                git checkout ${{ github.sha }}
                docker build -t balbinkatest .
                docker container rm --force dast
                docker run -p 5000:5000 --name dast -d balbinkatest

          - name: zap scan
            uses: zaproxy/action-full-scan@v0.13.0
            with:
              target: 'http://${{ secrets.DAST_HOST }}:5000'
              allow_issue_writing: false
              fail_action: true
              cmd_options: '-I'

          - name: Teardown after DAST
            if: always()
            uses: appleboy/ssh-action@v1
            with:
              host: ${{ secrets.DAST_HOST }}
              username: ${{ secrets.DAST_USER }}
              key: ${{ secrets.DAST_KEY }}
              port: 22
              script: |
                docker stop dast
                docker container rm dast
                docker image rm balbinkatest
                rm -rf TBO_balbinka

          - name: Log in to Docker Hub
            uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Extract metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
            with:
              images: ${{ vars.DOCKER_REPO }}

          - name: Build and push Docker image
            id: push
            uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
            with:
              context: ./Python/Flask_Book_Library/
              file: ./Python/Flask_Book_Library/Dockerfile
              push: true
              tags: ${{ steps.meta.outputs.tags }},${{ vars.DOCKER_REPO }}:${{ env.docker-tag }}
              labels: ${{ steps.meta.outputs.labels }}
